# Generated by Django 5.1.6 on 2025-02-10 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('wallet', 'Wallet'), ('mobile_banking', 'Mobile Banking')], max_length=100, unique=True),
        ),
    ]
