# Generated by Django 5.1.6 on 2025-02-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_organization_email_organization_website_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='email',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='website',
        ),
        migrations.AlterField(
            model_name='signature',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
